apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: heartbeat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: microsoft/mssql-server-linux
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
      - name: api
        image: localhost:5000/centos-python36-sqlodbc
        imagePullPolicy: Always
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: dev-lb
spec:
  selector:
    app: heartbeat
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer