# https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017
FROM microsoft/mssql-server-linux:2017-latest

ENV ACCEPT_EULA Y
ENV SA_PASSWORD e:.PU,,^66:%ihk

EXPOSE 1433:1433